account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import home, ArticleList, ArticleCreate, ArticleUpdate, ArticleDelete, Profile

app_name= "account"


urlpatterns = [
    path("", ArticleList.as_view(), name="home"),
    path("article/create", ArticleCreate.as_view(), name="article-create"),
    path("article/update/<int:pk>", ArticleUpdate.as_view(), name="article-update"),
    path("article/delete/<int:pk>", ArticleDelete.as_view(), name="article-delete"),
    path("profile/", Profile.as_view(), name="profile"),
]

blog/urls.py
from django.urls import path
#from .views import home, detail, category
from .views import ArticleList, ArticleDetail, ArticlePreview, CategoryList, AuthorList

app_name = "blog"
urlpatterns = [
    path('', ArticleList.as_view(), name='home'),
    path('page/<int:page_number>', ArticleList.as_view(),name='home'),
    path('articles/<slug:slug>', ArticleDetail.as_view() ,name='detail'),
    path('preview/<int:pk>', ArticlePreview.as_view() ,name='preview'),
    path('category/<slug:slug>', CategoryList.as_view() ,name='category'),
    path('category/<slug:slug>/page/<int:page_number>', CategoryList.as_view() ,name='category'),
    path('author/<slug:username>', AuthorList.as_view() ,name='author'),
    path('author/<slug:username>/page/<int:page_number>', AuthorList.as_view() ,name='author')


]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login , Register, activate
urlpatterns = [
    path('',include('blog.urls')),
    path('',include('django.contrib.auth.urls')),
    path("login/", Login.as_view(), name="login"),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path("register/", Register.as_view(), name="register"),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    activate, name='activate'),
    path('comment/', include('comment.urls')),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
#from django.contrib.auth.models import User
from account.models import User
from django.utils import timezone
from django.utils.html import format_html
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from extensions.utils import jalali_converter
from ckeditor.fields import RichTextField
# Managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)
# Models

class Category(models.Model):

    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name="زیر دسته")
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id', 'position']


    def __str__(self):
        return self.title
    objects = CategoryManager()

class Article(models.Model):

    STATUS_CHOISES = (
        ('d','پیش نویس'),     #draft
        ('p','منتشر شده'),    #published
        ('i','در حال بررسی'), #investigationn
        ('b','برگشت داده شده'),#back
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="articles", verbose_name="نویسنده")
    title = models.CharField(max_length=200, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی', related_name="articles")
    time_to_read = models.IntegerField(verbose_name="مدت زمان مطالعه به دقیقه")
    description = RichTextField(blank=True,null=True,verbose_name="محتوا")
    thumbnail = models.ImageField(upload_to="images", verbose_name='تصویر مقاله')
    publish = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_spical = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    status = models.CharField(max_length=1,choices=STATUS_CHOISES, verbose_name='وضعیت')
    comments = GenericRelation(Comment)
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"

    def get_absolute_url(self):
        return reverse("account:home")

    # def category_published(self):
    #     return self.category.filter(status=True)
    
    def thumbnail_tag(self):
        return format_html("<img width='70px' height='60px' style='border-radius: 5px' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description="عکس"
    
    def category_to_str(self):
        return ",".join([category.title for category in self.category.active()])
    category_to_str.short_description="دسته بندی"

    objects = ArticleManager()

blog/forms.py
from django import forms
from .models import *
from ckeditor.fields import RichTextField


class PostForm(forms.ModelForm):
    description = RichTextField()

    class Meta:
        model  = Post
        fields = ('description',)

blog/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
#from django.contrib.auth.models import User
from account.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from account.mixins import AuthorAccessMixin
#from django.http import HttpResponse

# # Create your views here.
# def home(request, page_number=1):

#     articles_list = Article.objects.filter(status='p')
#     paginator = Paginator(articles_list, 3)
#     page_number = request.GET.get('page')
#     articles = paginator.get_page(page_number)
#     context = {
#        "articles": articles, 
#           #"articles": Article.objects.filter(status='p')
#           # or  "articles": Article.objects.published()NL
#     }
#     return render(request, "blog/index.html" , context)


class ArticleList(ListView):
    #context_object_name = "articles"
    queryset = Article.objects.published()
    #template_name =  "blog/index.html" # in home its not nessosary
    paginate_by=3
    

class ArticleDetail(DetailView):
    #template_name =  "blog/detail.html" 
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)


class ArticlePreview(AuthorAccessMixin, DetailView):
    #template_name =  "blog/detail.html" 
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)


# def detail(request, slug):
#     context = {
#        "article": get_object_or_404(Article, slug=slug, status="p"),

#     }
#     return render(request,"blog/detail.html" , context)   

# def category(request, slug, page_number=1):
#     category = get_object_or_404(Category, slug=slug, status=True)
#     articles_list = category.articles.published()
#     page_number = request.GET.get('page')
#     paginator = Paginator(articles_list, 3)
#     articles = paginator.get_page(page_number)
#     context = {
#          "category": category,
#          "articles": articles
#    }
#     return render(request, "blog/category.html" , context)


class CategoryList(ListView):
    template_name =  "blog/category_list.html"
    paginate_by=3

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    template_name =  "blog/author_list.html"
    paginate_by=3

    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load comment_tags %} 
{% include_bootstrap %}

{% block title %} | {{article.title}} {% endblock %}

{% block main %}

<!-- Page Header-->
<header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>{{article.title}}</h1>
                {% if article.is_spical %}
                    <span class="badge" style="color: #f96767; font-size: 20px;">ویژه</span>
                {% endif %}
                    <time>{{article.jpublish}}</time>
                    <p class="post-subtitle"style="margin-top:5px">مدت زمان مطالعه {{article.time_to_read}} دقیقه</p>
                    <span class="subheading"></span>
                </div>
            </div>
        </div>
    </div>
</header>


<!-- Post Content-->
<article class="mb-4">
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center text-justify">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% if article.is_spical %}
                {% if user.is_athenticated and user.is_special_user or user == object.author or user.is_superuser %}
                    {{article.description|safe}}
                {% else %} 
                {{article.description|striptags|truncatewords:20}}
                    <p class="alert alert-warning">برای دیدن این مقاله باید <a href="#" class="alert-link">اشتراک ویژه </a>داشته باشید</p>
                {% endif %}
            {% else %}
                {{article.description|safe}}
            {% endif %}
            
        {% render_comments object request %}

        </div>

    </div>
</div>
</article>
{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block 'header' %} {% endblock %}

{% block 'previous_page_url' %}
    {% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}

{% block 'next_page_url' %}
    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}
{% block 'header' %}
    <h3 class="alert alert-primary text-center">نویسنده :{{author.get_full_name}}</h3>
{% endblock %}

{% block 'previous_page_url' %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block 'next_page_url' %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> نت بلاگ {% block title %} {% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet" />
    </head>
    <body>
    

    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'blog:home' %}">نت بلاگ</a>
        {% category_navbar %}
    </div>
    {% if not user.is_authenticated %}
    <div class="account-section" style="display: flex; margin-left: 100px;">
        <button  class="btn" style="height: 100px; width: 100px; font-size: 13px;" ><a href="{% url 'register' %}">ثبت نام</a></button>
        <button class="btn"><a href="{% url 'login' %}">ورود</a></button>

    </div>
    {% else %}
        <div ><a style="margin-left: 40px; margin-top: 10px; font-size:13px;" href={% url 'account:profile' %}> مشاهد داشبورد </a></div>
    {% endif%} 

    </nav>
        {% block main %}
            
        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; NetBlog 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}
{% block 'header' %} 
    <h3 class="alert alert-primary text-center">دسته بندی:{{category.title}}</h3>
{% endblock %}

{% block 'previous_page_url' %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block 'next_page_url' %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block main %}

<!-- Page Header-->

<header class="masthead" style="background-image: url('{% static "blog/assets/img/home.jpg" %}')">
<div class="container position-relative px-4 px-lg-5">
	<div class="row gx-4 gx-lg-5 justify-content-center">
		<div class="col-md-10 col-lg-8 col-xl-7">
			<div class="site-heading">
				<h1>وبلاگ</h1>
			</div>
		</div>
	</div>
</div>
</header>

{% block 'header' %}{% endblock %}
<!--
	detailview = object.felan
	listview = object_list

-->

<!-- Main Content-->
<div class="container px-4 px-lg-5">
	<div class="row gx-4 gx-lg-5 justify-content-center">
		<div class="col-md-10 col-lg-8 col-xl-7">
		  
			<!-- Post preview-->
			<div class="post-preview">
				{% for article in object_list %}
				<a href="{% url 'blog:detail' article.slug %}"><h2 class="post-title">{{article.title}}
				{% if article.is_spical %}
					<span class="badge" style="color:#f96767; font-size:20px;">ویژه</span>
				{% endif %}
				</h2> </a>

				<h5 class="post-subtitle">{{article.description|striptags|truncatewords:20}}</h5>
				<p class="post-subtitle">
					 منتشر شده توسط
					<a href="{% url 'blog:author' article.author %}">{{article.author.get_full_name}}</a>در
					{{article.jpublish}}

				</p>
				<p class="post-meta" style="margin-top: 1px;">
					<p class="post-subtitle">مدت زمان مطالعه {{article.time_to_read}} دقیقه</p>
				</p>
				<div>
					{% for cat in article.category.active %}
					<a href="{% url 'blog:category' cat.slug %}"># {{cat.title}}</a>
					{% endfor %}
				</div>
			
			{% endfor %}
			<!-- Divider-->
			<hr class="my-4" />
			
		   <!-- Pager-->
		 {% if is_paginated %}
			 {% if page_obj.has_previous %}
			<div style="display:flex; text-align: center;">
			 <div class="d-flex justify-content-end mb-4 ml-3"><a class="btn btn-primary text-uppercase mr-3" href="{% url 'blog:home' %}?page={{page_obj.previous_page_number}}">پست های جدید </a>
			 {% endif %}
			 {% if page_obj.has_next %}
			 
			 </div>
			 <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase mr-3" href="{% url 'blog:home' %}?page={{page_obj.next_page_number}}">پست های قدیمی </a> 
				
			 {% endif %}
			 </div>
			 </div>
		 {% endif %}
		</div>
		</div>
	</div>
</div>

{% endblock %}